source ('acciones.R')

Cortar("pan")
Cortar("Palta")
Cortar("Naranjas")
Calentar("Cafe")
Calentar("pan cortado")
Moler("palta cortada")
Preparar("naranjas cortadas")
Preparar("harina","huevos")
CalentarSarten()
Preparar("masa de panqueques","sarten caliente")
Rellenar("panqueques")
Servir("pan tostado con palta","panqueques con manjar","jugo de naranjas","cafe caliente")